#!/bin/bash
sudo apt update -qq
sudo apt upgrade -qq
sudo apt autoremove -qq
#sudo apt install edubuntu-desktop -qq
sudo apt install ubuntu-mate-desktop -qq
sudo apt install shellinabox novnc apache2 -qq
sudo apt install tigervnc-common tigervnc-xorg-extension tigervnc-standalone-server -qq
sudo apt install curl git wget expect -qq
mkdir -p ~/.vnc
curl https://raw.githubusercontent.com/ayeai/ayevdi/master/xstartup.sample > ~/.vnc/xstartup

sudo adduser --disabled-password --gecos "" ayeuser && (echo ayeuser:ayeaye | sudo chpasswd)

prog=/usr/bin/vncpasswd
mypass="q1w2e3"
vpass="123456"

/usr/bin/expect <<EOF
spawn "$prog"
expect "Password:"
send "$mypass\r"
expect "Verify:"
send "$mypass\r"
expect "Would you like to enter a view-only password (y/n)?"
send "y\r"
expect "Password:"
send "$vpass\r"
expect "Verify:"
send "$vpass\r"
expect eof
exit
EOF
