#!/bin/bash
sudo apt update -y 
sudo apt upgrade -y
sudo apt autoremove -y
sudo apt install edubuntu-desktop -y
sudo apt install ubuntu-mate-desktop -y
sudo apt install shellinabox novnc apache2 -y
sudo apt install tigervnc-common tigervnc-xorg-extension tigervnc-standalone-server -y
sudo apt install curl git wget expect -y
mkdir -p ~/.vnc
curl https://raw.githubusercontent.com/ayeai/ayevdi/master/xstartup.sample > ~/.vnc/xstartup

prog=/usr/bin/vncpasswd
mypass="q1w2e3"
vpass="123456"

/usr/bin/expect <<EOF
spawn "$prog"
expect "Password:"
send "$mypass\r"
expect "Verify:"
send "$mypass\r"
expect "Would you like to enter a view-only password (y/n)?"
send "y\r"
expect "Password:"
send "$vpass\r"
expect "Verify:"
send "$vpass\r"
expect eof
exit
EOF
